-- AUDITAR BORRADO TRIGGERS

CREATE TABLE historico_prestamos(
    ID_PRESTAMO CHAR(5),
    ID_SOCIO CHAR(5),
    ID_EDICION CHAR(6),
    NUMERO INTEGER,
    FECHA_BORRADO TIMESTAMP
);

CREATE OR REPLACE TRIGGER auditar_borrado_prestamo 
BEFORE DELETE ON PRESTAMO FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO historico_prestamos VALUES (:OLD.ID_PRESTAMO, :OLD.ID_SOCIO, :OLD.ID_EDICION, :OLD.NUMERO, CURRENT_TIMESTAMP);
END;
/